on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ror es
        uses: actions/checkout@v2
        with:
          path: main
          
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          path: docs 
          repository: beshu-tech/readonlyrest-docs
          token: ${{ secrets.GH_PAT }}
          
      - run: |
          mv docs main/readonlyrest-docs
          cd main 
          git config --global advice.detachedHead false
          bash -x ci/actionstrings/run.sh
          cd readonlyrest-docs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "commit new action strings" || true
          git push || true
